LBlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from blog import views as blog_views
# from ueditor import urls


urlpatterns = [
    url(r'^love_liuliancao/', include(admin.site.urls)),
    # url(r'^role/', include('role.urls')),
    # url(r'^captcha/', include('captcha.urls')),
    # blog about.

    # url(r'^ueditor/', include(DjangoUeditor_urls)),
    url(r'^controller', 'ueditor.controller.Get_Actions'),
    # for our built-in ajax post view
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<category_slug>[^/]+)/$', views.CategoryView.as_view(), name="category"),
    url(r'^article/(?P<article_slug>[^/]+)/$', views.article_detail, name="article"),
    url(r'^archive/(?P<year>\d+)/(?P<month>\d+)$', views.ArchiveView.as_view(), name='archive'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^search/(?P<search_key>.*)/$', views.SearchView.as_view(), name="search")
]

ueditor/models.py
from django.db import models

# Create your models here.
# class blog(models.Model):
#     title = models.CharField(max_length=200,verbose_name='标题')
#     content = models.TextField('内容')
#     pub_date=models.DateTimeField(verbose_name='发表日期')
#     hit_count=models.IntegerField(verbose_name='浏览次数',default=0)

ueditor/controller.py
'''
Created on Mar 21, 2015

@author: root
'''
import json
import LBlog.usettings as usettings
from django.conf import settings 
from django.http.response import HttpResponse
import datetime,random
import os
from django.views.decorators.csrf import csrf_exempt
import codecs
from gunicorn.http.wsgi import Response
import base64

def GetUeditorSettings():
    content = json.dumps(usettings.UploadSettings)  
    return content

def GetValue(key):
    return usettings.UploadSettings.get(key)

def configAction(request): 
    content = GetUeditorSettings()
    callback = request.GET.get("callback")
    if callback:
        return HttpResponse("{0}{1}".format(callback, content))
    return HttpResponse(content)

class initJsonResult(object):
    def __init__(self,state="未知的错误",url="",title="",original="",error="null"):
        super(initJsonResult).__init__()
        self.state = state
        self.url = url
        self.title = title
        self.original = original
        self.error = error

def bulidJsonResult(result):
    jsondata = {
                "state":result.state,
                "url":result.url,
                "title":result.title,
                "original":result.original,
                "error":result.error
                }
    return json.dumps(jsondata)

def buildFileName(filename):
    dt = datetime.datetime.now()
    name,ext = os.path.splitext(filename)
    return "%s-" % name + dt.strftime("%Y%m%d%M%H%S{0}{1}".format(random.randint(1,653323), ext))
    
def checkFileName(filename,AllowExtensions):
    exts = list(AllowExtensions)
    name,ext = os.path.splitext(filename)
    return ext in exts

def checkFileSize(filesize,SizeLimt):
    return filesize < SizeLimt

def checkDirExit(saveDir):
    if not os.path.exists(saveDir):
        os.makedirs(saveDir)
        
@csrf_exempt
def uploadFile(request,UploadFieldName,SizeLimit,AllowExtensions,SavePath,Base64,Base64Filename):
    
    action = request.GET.get("action")
#     print(action)
    result = initJsonResult()
    
    if action == "uploadscrawl":
        filename = Base64Filename
        saveName = buildFileName(filename)
        webUrl = SavePath + saveName
        saveDir = settings.MEDIA_ROOT + SavePath
        checkDirExit(saveDir)
        savePath = settings.MEDIA_ROOT + webUrl
        try:
            content = request.POST.get(UploadFieldName)
            f = open(savePath,'wb')
            f.write(base64.urlsafe_b64decode(content))
            f.close()
            result.state = "SUCCESS"
        except Exception as e:
            e.message
            result.state = "ERROR"
        result.url = saveName
        result.title = saveName
        result.original =saveName
        response = HttpResponse(bulidJsonResult(result))
        response["Content-Type"]="text/plain"
        return response
    else:
        buf = request.FILES.get(UploadFieldName)
        filename = buf.name
        if not checkFileName(filename, AllowExtensions):
            result.error = "不允许的文件格式"
            return HttpResponse(bulidJsonResult(result))
        if not checkFileSize(buf.size, SizeLimit):
            result.error = "文件大小超出了限制"
            return HttpResponse(bulidJsonResult(result))
        
        try:
            saveName = buildFileName(filename)
            webUrl = SavePath + saveName
#             print(settings.MEDIA_ROOT)
            saveDir = settings.MEDIA_ROOT + SavePath
            checkDirExit(saveDir)
            savePath = settings.MEDIA_ROOT + webUrl
            f = codecs.open(savePath, "wb")
            for chunk in buf.chunks():
                f.write(chunk)
            f.flush()
            f.close()
            result.state = "SUCCESS"
            result.url = saveName
            result.title = saveName
            result.original =saveName
            response = HttpResponse(bulidJsonResult(result))
            response["Content-Type"]="text/plain"
            return response
        except:
            result.error = "ERROR"
            return HttpResponse(bulidJsonResult(result))
@csrf_exempt
def listFileManager(request,imageManagerListPath,imageManagerAllowFiles,listsize):

    start = int(request.GET.get("start",0))
    size = int(request.GET.get("size",GetValue(listsize)))
    localPath = settings.MEDIA_ROOT + imageManagerListPath
    filelist = []
    exts = list(imageManagerAllowFiles)
    index = start
    for imagename in os.listdir(localPath):
        name,ext = os.path.splitext(imagename)
        if ext in exts:
            filelist.append(dict(url=imagename))
            index += 1
            if index - start>=size:
                break
    jsondata = {"state":"SUCCESS","list":filelist,"start":start,"size":size,"total":index}
    return HttpResponse(json.dumps(jsondata))

@csrf_exempt
def uploadimageAction(request):
    AllowFiles = GetValue("imageAllowFiles") 
    MaxSize = GetValue("imageMaxSize")
    FieldName = GetValue("imageFieldName")
    SavePath = GetValue("imagePath")
    return uploadFile(request,FieldName,MaxSize,AllowFiles,SavePath,False,'')
@csrf_exempt
def uploadvideoAction(request):
    AllowFiles = GetValue("videoAllowFiles") 
    MaxSize = GetValue("videoMaxSize")
    FieldName = GetValue("videoFieldName")
    SavePath = GetValue("videoPath")
    return uploadFile(request,FieldName,MaxSize,AllowFiles,SavePath,False,'')
@csrf_exempt
def uploadfileAction(request):
    AllowFiles = GetValue("fileAllowFiles") 
    MaxSize = GetValue("fileMaxSize")
    FieldName = GetValue("fileFieldName")
    SavePath = GetValue("filesPath")
    return uploadFile(request,FieldName,MaxSize,AllowFiles,SavePath,False,'')
@csrf_exempt
def listimageAction(request):
    imageManagerListPath = GetValue("imageManagerListPath")
    imageManagerAllowFiles = GetValue("imageManagerAllowFiles")
    imagelistsize = GetValue("imageManagerListSize")
    return listFileManager(request,imageManagerListPath,imageManagerAllowFiles,imagelistsize)

@csrf_exempt
def ListFileManagerAction(request):
    fileManagerListPath = GetValue("fileManagerListPath")
    fileManagerAllowFiles = GetValue("fileManagerAllowFiles")
    filelistsize = GetValue("fileManagerListSize")
    return listFileManager(request,fileManagerListPath,fileManagerAllowFiles,filelistsize)

def uploadscrawlAction(request):
    MaxSize = GetValue("scrawlMaxSize")
    FieldName = GetValue("scrawlFieldName")
    SavePath = GetValue("scrawlPath")
    return uploadFile(request,FieldName,MaxSize,'',SavePath,True,'scrawlFile.png')

actions = {
            "config" : configAction,
            "uploadimage" : uploadimageAction,
            "uploadvideo":uploadvideoAction,
            "uploadfile":uploadfileAction,
            "listimage":listimageAction,
            "listfile":ListFileManagerAction,
            "uploadscrawl":uploadscrawlAction,
           }

@csrf_exempt
def Get_Actions(request):
    action = request.GET.get("action")
    print(action)
    return actions.get(action)(request)

ueditor/views.py
from django.shortcuts import render_to_response

# Create your views here.
def index(request):
    return render_to_response('index.html')

templates/baidutongji.html
<!-- 这里放统计的代码 -->

<!-- 百度统计 begin-->
<div style="display:none" hidden>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Fab8b04b0bf640ac196520db1cd029664' type='text/javascript'%3E%3C/script%3E"));
</script>
</div>
<!-- 百度统计 end-->

templates/base.html
<!DOCTYPE html>
{#<html lang="zh-cn">#}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="liuliancao's homepage">
    <meta name="author" content="liuliancao">
    {% load staticfiles %}
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lblog.css' %}" rel="stylesheet">
    <!--导入JQ和bootstraps的js脚本-->
    <!-- Bootstrap core JavaScript
    ==================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'ueditor/third-party/SyntaxHighlighter/shCore.js' %}"></script>
    <link rel="stylesheet" href="{% static 'ueditor/third-party/SyntaxHighlighter/shCoreDefault.css' %}">
    <script type="text/javascript">
        SyntaxHighlighter.all();
        $(function(){
                //当滚动条的位置处于距顶部100像素以下时，跳转链接出现，否则消失
                $(function () {
                    $(window).scroll(function(){
                        if ($(window).scrollTop()>100){
                            $("#back-to-top").fadeIn(1500);
                        }
                        else
                        {
                            $("#back-to-top").fadeOut(1500);
                        }
                    });

                    //当点击跳转链接后，回到页面顶部位置

                    $("#back-to-top").click(function(){
                        $('body,html').animate({scrollTop:0},1000);
                        return false;
                    });
                });
            });
    </script>
	<script>
		var _hmt = _hmt || [];
		(function() {
  			var hm = document.createElement("script");
  			hm.src = "//hm.baidu.com/hm.js?1161614d36c8a808628d5dea6e27a45f";
  			var s = document.getElementsByTagName("script")[1]; 
  			s.parentNode.insertBefore(hm, s);
		})();
	</script>

     <!--多说js加载开始，一个页面只需要加载一次 -->
    <script type="text/javascript">
        var duoshuoQuery = {short_name:"liuliancao"};
{#        (function() {#}
{#            var ds = document.createElement('script');#}
{#            ds.type = 'text/javascript';ds.async = true;#}
{#            ds.src = '{% static 'js/embed.js' %}';#}
{#            ds.charset = 'UTF-8';#}
{#            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ds);#}
{#        })();#}
    </script>
    <script src="{% static 'js/embed.js' %}"></script>
    <!--多说js加载结束，一个页面只需要加载一次 -->
    <title>{% block title %}liuliancao的小站{% endblock %}</title>
</head>
<body>
    <!--回到顶部锚点-->
    <a name="top"></a>
    <!--回到顶部锚点结束-->
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <div id="category" class="noselect">
                     <div id="category-title">
                        <ul>
                            <li>分类：</li>
                            <li class="cat-item"><a href="{% url 'blog:index' %}">主页</a></li>
                            {% for category in category_list %}
                                <li class="cat-item">
                                    <a href="{% url 'blog:category' category.slug %}">
                                        {{ category.name }}
                                    </a>
                                </li>
                            {% endfor %}
                                <li class="cat-item">
                                    <a href="{% url 'blog:about' %}">关于</a>
                                </li>
                        </ul>
                     </div>
                 </div>
                <div id="bd" class="wrp clear-fix">
                    <div id="main">
                        {% block body_block %}{% endblock %}

                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="right_title">
                    <span title="全站搜索" class="title">全站搜索</span>
                </div>
                <div class="search">
                    <input id="search_input" type="search" placeholder="Search"
                           onkeypress="if(event.keyCode==13){search_btn.click();return false;}">
                    <button class="btn-info" type="submit" name="search_btn" id="search_btn">搜索</button>
                </div>
                <div class="right_title">
                    <span title="标签" class="title">标签</span>
                </div>
                <div class="list-group">
                    {% for tag in tag_list %}
                        <a href="{% url 'blog:tag' tag.pk %}" class="list-group-item"><span
                                class="badge"></span>{{ tag.name }}</a>
                    {% endfor %}
                </div>
                <!-- archive -->
                <div class="right_title">
                    <span title="文章归档" class="title">文章归档</span>
                </div>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% if date_archive %}
                        {% for year,months in date_archive %}
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                    <h4 class="panel-title">
                                        <a role="button" data-toggle="collapse" data-parent="#accordion"
                                           href="#collapse{{ forloop.counter }}"
                                           aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                            {{ year }} 年
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                     aria-labelledby="heading{{ forloop.counter }}">
                                    <div class="panel-body">
                                        {% for month in months %}
                                            <a href="{% url 'blog:archive' year month %}"><p>{{ month }} 月</p></a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>暂时没有内容</p>
                    {% endif %}
                </div>
                <!-- archive end -->
                <div class="right_title">
                    <span title="友链" class="title">友链</span>
                </div>
                <a href="http://weibo.com/liuliancao" target="_blank">
                    <img src="{% static 'images/head_image.jpg' %}" width="30" height="30" id="weibo_headimg"/>&nbsp;
                    欢迎互友
                </a>
                <div class="right_title">
                        <span title="最近访客" class="title">最近访客</span>
                </div>
                <div class="ds-recent-visitors"></div>
        </div>
    </div>

    <!--回到顶部部分-->
    <p id="back-to-top"><a href="#top"><span></span>返回顶部</a></p>
    <!--回到顶部结束-->
    <script type="application/javascript">
        {# 搜索部分 #}
        var search_button = document.getElementById('search_btn');
        search_button.onclick = function(){
            var search_key = document.getElementById('search_input').value;
            if(search_key == ''){
                alert('搜索框的内容不能为空！');
            }else{
                window.location.href="/search/" + search_key;
                return false;
            }
        };
    </script>
</body>
</html>

templates/ueditor.html
<!-- 配置文件 -->
{% load staticfiles %}
<script type="text/javascript" src="{% static 'ueditor/ueditor.config.js' %}"></script>
<!-- 编辑器源码文件 -->
<script type="text/javascript" src="{% static 'ueditor/ueditor.all.js' %}" ></script>
<!-- 实例化编辑器 -->
<script type="text/javascript">
    var ue = UE.getEditor('id_content');
    var article_html = document.getElementById('id_html').value;
    ue.ready(function() {
    ue.setContent(article_html);
    });
</script>
 